/**
 * PPA (Power Purchase Agreement) View Component
 * Displays the formatted PPA document based on form data
 */

'use client';

import React, { useEffect } from 'react';
import type { PPAData } from '@/types/ppa';

interface Props {
  data: PPAData;
}

const PPAView: React.FC<Props> = ({ data }) => {
  // Construct full address
  const fullAddress = `${data.village} District: ${data.district}, State: ${data.state}, PIN Code: ${data.pinCode}`;
  const fullParagraphAddress = `${data.prosumerName} S/O ${data.fatherName} at. ${fullAddress}`;

  // Add print styles
  useEffect(() => {
    const style = document.createElement('style');
    style.textContent = `
      @media print {
        body * {
          visibility: hidden;
        }
        #ppa-document, #ppa-document * {
          visibility: visible;
        }
        #ppa-document {
          position: absolute;
          left: 0;
          top: 0;
          width: 100%;
        }
        .no-print {
          display: none !important;
        }
      }
    `;
    document.head.appendChild(style);
    return () => {
      document.head.removeChild(style);
    };
  }, []);

  return (
    <div className="bg-white p-8 max-w-4xl mx-auto my-8 shadow-lg print:shadow-none">
      {/* Print Button */}
      <div className="no-print mb-4 flex justify-end">
        <button
          onClick={() => window.print()}
          className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-6 rounded"
        >
          🖨️ Print Agreement
        </button>
      </div>

      <div id="ppa-document" className="font-serif leading-relaxed text-black print:p-8">
        {/* Header - Placeholder for image */}
        <div className="text-center mb-6">
          <div className="border-2 border-gray-300 p-4 bg-gray-50">
            <p className="text-sm text-gray-600">CSPDCL Header Image</p>
            <p className="text-xs text-gray-500">(Upload header.jpg to display)</p>
          </div>
        </div>

        <h1 className="text-center text-xl font-bold underline mb-6">
          POWER PURCHASE AGREEMENT FOR RTS PLANTS
        </h1>

        <p className="mb-4 text-justify">
          This Power Purchase Agreement is made and entered into at Sub Division on the{' '}
          <strong className="bg-yellow-100 px-1">{data.agreementDate}</strong> between CHHATTISGARH STATE POWER 
          DISTRIBUTION CO. LTD. RAIPUR (hereinafter referred to as CSPDCL /Licensee), a company incorporated 
          under the provisions of the Companies Act, 2013, having its head office at Vidyut Sewa Bhawan, 
          Dangania, Raipur – 492013, Chhattisgarh, India, which expression shall, unless repugnant to the 
          subject, context or meaning thereof, be deemed to mean and include its successors, authorized 
          representatives and permitted assigns of the First part.
        </p>

        <p className="text-center font-bold text-lg my-4">And</p>

        <p className="mb-4 text-justify">
          <strong className="bg-yellow-100 px-1">{data.consumerId}</strong> having its premises at.{' '}
          <strong className="bg-yellow-100 px-1">{data.prosumerName}</strong> S/O{' '}
          <strong className="bg-yellow-100 px-1">{data.fatherName}</strong> at.{' '}
          <strong className="bg-yellow-100 px-1">{fullAddress}</strong>, herein after referred to the 
          'Prosumer' as party on the SECOND PART.
        </p>

        <p className="mb-4 text-justify">
          The Chhattisgarh State Electricity Regulatory Commission (hereinafter referred to as "the Commission") 
          has notified Chhattisgarh State Electricity Regulatory Commission (Grid Interactive Distributed 
          Renewable Energy Sources) Regulations, 2019 (hereinafter referred to as- "CSERC Distributed Solar 
          energy Regulations 2019") wherein modalities for purchase annual surplus energy (excess energy 
          injected to CSPDCL's distribution system by the RTS Plants having capacity 1kWp & above after 
          netting off) by distribution licensee and other related dispensations are suitably addressed. Also, 
          as per provisions in the CSERC Distributed Solar energy Regulations 2019, power generated by such 
          RTS Plants will also qualify for CSPDCL's renewable purchase obligation.
        </p>

        <p className="mb-4 text-justify">
          Whereas Prosumer has set up <strong className="bg-yellow-100 px-1">{data.plantCapacity} kWp</strong>{' '}
          Roof-Top Solar Power Plant at. <strong className="bg-yellow-100 px-1">{fullParagraphAddress}</strong>{' '}
          for their captive use whereas Prosumer has offered annual surplus solar power (excess energy 
          injected to CSPDCL's distribution system by the RTS Plants having capacity 1kWp & above after 
          netting off) for sale to the Licensee in accordance to CSERC Distributed Solar energy Regulations 
          2019, also the following Regulations and codes, as amended from time to time: -
        </p>

        <ul className="list-disc ml-8 mb-4">
          <li>CEA's (Technical Standards for connectivity of the Distributed Generating Resources) Regulations, 2013. POWER</li>
          <li>Central Electricity Authority (Installation and Operation of Meters) Regulations, 2006</li>
          <li>Central Electricity Authority (Measures relating to safety and electric supply) Regulations, 2010</li>
          <li>Chhattisgarh State Electricity Grid Code, 2011</li>
          <li>CSERC Supply Code, 2011</li>
        </ul>

        <p className="mb-4">
          NOW This agreement witnesses and the parties hereto have agreed as below: <br />
          <span className="underline">Part 1: Definitions and interpretations</span>
        </p>

        <p className="mb-4">In this Agreement, the following words and expressions shall have the respective meanings set forth herein:</p>

        <ul className="list-disc ml-8 mb-4">
          <li>"Grid Meter/Bidirectional Meter" or "GM" means import and export meter on the basis of which energy bills shall be raised by Distribution licensee;</li>
          <li>"Solar Meter/Generating Meter" or "SM" means a meter for used for accounting and billing of electricity generated by the Rooftop PV Solar Power Generating Plant;</li>
          <li>All other words and phrases shall have the same meaning as defined in the CSERC Distributed Solar Energy Regulations 2019.</li>
        </ul>

        {/* Terms and Conditions */}
        <ol className="list-decimal ml-8 mb-4 space-y-3">
          <li>Regulations, guidelines or terms and conditions of power purchase by the licensee from RTS Plants specified by the Commission from time to time shall be acceptable and binding on both the parties.</li>
          
          <li><strong>TARIFF: Rs. per kWh</strong> for useful life of RTS plants. The tariff shall be governed by the modalities specified in related Regulations, guidelines or terms and conditions of power purchase by the licensee from RTS Plants specified by the Commission from time to time.</li>
          
          <li><strong>Payment of Dues:</strong> CSPDCL is obligated to make direct payment of dues into the bank account of Prosumer towards excess electricity, if any, at the end of settlement period by 15th May of ensuing financial year.</li>
          
          <li>CSPDCL shall accept the power as per the useful life of the RTS PLANTS unless the prosumer ceases to be a consumer of the licensee or the RTS PLANTS is abandoned, whichever is earlier.</li>
          
          <li>In case the prosumer leaves the system, excess electricity shall be considered as inadvertent injection and shall not be paid for by the licensee.</li>
          
          <li>Any other generators operating in parallel to the RTS plants shall not be eligible for payment at the tariff as specified in Clause 2.</li>
          
          <li><strong>METERING</strong> - The Grid Meter (GM) and Solar meter shall be interface type as envisaged in the CEA metering regulations.</li>

          <li><strong>Dispute Resolution:</strong> Both parties agree to resolve the dispute arising out of this agreement as per mechanism established under Section 42 of Electricity Act, 2003.</li>
          
          <li><strong>FORCE-MAJEURE AND OUTAGE:</strong> Any event which is beyond the control of the agencies involved which they could not foresee.</li>

          <li>The Prosumer agrees that in case of a power outage on licensees system, Renewable Energy system will disconnect/ isolate automatically.</li>
          
          <li><strong>DURATION:</strong> The agreement shall come into effect for all purposes from the date of commercial operation (COD) of the RTS plants and shall remain valid for their useful life from the date of COD.</li>
        </ol>

        <p className="mt-12 mb-8">IN WITNESS WHEREOF parties through their respective duly authorized Officer/ representative have signed this agreement</p>

        {/* Signature Section */}
        <div className="grid grid-cols-2 gap-8 mt-16">
          <div>
            <p className="font-bold mb-2">WITNESSES (Consumer)</p>
            <div className="border-b border-black mt-12 mb-1"></div>
            <div className="border-b border-black mt-12 mb-1"></div>
          </div>

          <div className="text-right">
            <p className="font-bold mb-2">PROSUMER</p>
            <p className="text-lg font-bold mt-12">
              <span className="bg-yellow-100 px-1">{data.prosumerName}</span>
            </p>
          </div>
          
          <div>
            <p className="font-bold mb-2">WITNESSES (CSPDCL)</p>
            <div className="border-b border-black mt-12 mb-1"></div>
            <div className="border-b border-black mt-12 mb-1"></div>
          </div>

          <div className="text-right">
            <p className="font-bold mb-2">CSPDCL Authority</p>
            <div className="border-b border-black mt-12 mb-1"></div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PPAView;
